name: Build e Release Automático

on:
  push:
    tags:
      - 'v*'  # Só roda quando uma tag tipo v0.4.16-alpha1 for criada

jobs:
  build:
    name: Build e Geração de Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Preparar build
        run: |
          mkdir dist
          cp -r * dist/  # Copia todos os arquivos para a pasta dist

      - name: Criar tar.gz
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          FILENAME="linux-amd64-casaos-app-management-${TAG_NAME}.tar.gz"
          tar -czf $FILENAME dist/
          mv $FILENAME dist/

      - name: Gerar checksums.txt
        run: |
          cd dist
          sha256sum * > checksums.txt
          cd ..

      - name: Publicar na Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
